export const SWAPI_API = process.env.REACT_APP_SWAPI_API;
export const SWAPI_PEOPLE = process.env.REACT_APP_SWAPI_PEOPLE;

export const REACT_APP_SWAPI_PEOPLE_PAGE =
  process.env.REACT_APP_SWAPI_PEOPLE_PAGE;

export const REACT_APP_SWAPI_PEOPLE_IMAGE =
  process.env.REACT_APP_SWAPI_PEOPLE_IMAGE;

export const REACT_APP_SWAPI_PEOPLE_IMAGE_FORMAT =
  process.env.REACT_APP_SWAPI_PEOPLE_IMAGE_FORMAT;

export const REACT_APP_SWAPI_PEOPLE_ALL =
  process.env.REACT_APP_SWAPI_PEOPLE_ALL;

export const REPO_NAME = process.env.REACT_APP_REPO_NAME;
